<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <!-- Ignore informational audit notices from failing build -->
    <WarningsNotAsErrors>NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
  </PropertyGroup>

  <!-- Global Usings for Test Projects -->
  <ItemGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
