using NikiAI.Core.Tasks;
using NikiAI.Core.Tools;

namespace NikiAI.Core.Agent;

/// <summary>
/// Represents a single message in an LLM conversation.
/// </summary>
public record AgentMessage(string Role, string Content, DateTimeOffset? Timestamp = null)
{
    public static AgentMessage System(string content) => new("system", content, DateTimeOffset.UtcNow);
    public static AgentMessage User(string content) => new("user", content, DateTimeOffset.UtcNow);
    public static AgentMessage Assistant(string content) => new("assistant", content, DateTimeOffset.UtcNow);
}

/// <summary>
/// Token consumption metrics for an LLM response.
/// </summary>
public record TokenUsage(int PromptTokens, int CompletionTokens, int TotalTokens);

/// <summary>
/// Structured request payload for chat completion.
/// </summary>
public record ChatCompletionRequest(
    IReadOnlyList<AgentMessage> Messages,
    string? Model = null,
    double? Temperature = null,
    int? MaxTokens = null,
    string? SystemPrompt = null
);

/// <summary>
/// Structured response payload from chat completion.
/// </summary>
public record ChatCompletionResponse(
    string Content,
    string? Model = null,
    TokenUsage? Usage = null,
    string? FinishReason = null
);

/// <summary>
/// Result of an explicit connection/diagnostic test to an AI provider.
/// </summary>
public record ConnectionTestResult(
    bool IsSuccess,
    long LatencyMs,
    string? ModelUsed = null,
    string? ErrorMessage = null
)
{
    public static ConnectionTestResult Success(long latencyMs, string modelUsed) =>
        new(true, latencyMs, modelUsed, null);

    public static ConnectionTestResult Failure(long latencyMs, string errorMessage) =>
        new(false, latencyMs, null, errorMessage);
}

/// <summary>
/// Configuration for an AI provider endpoint.
/// </summary>
public class ProviderConfig
{
    public string ProviderId { get; set; } = "openai-compatible";
    public string ProviderName { get; set; } = "OpenAI Compatible / Local LLM";
    public string EndpointUrl { get; set; } = "https://api.openai.com/v1";
    public string ModelName { get; set; } = "gpt-4o-mini";
    public string ApiKeySecretKey { get; set; } = "ai_provider_api_key";
    public double Temperature { get; set; } = 0.7;
    public int MaxTokens { get; set; } = 2048;
}

/// <summary>
/// AI Provider abstraction interface.
/// Decouples agent orchestration from specific model vendors and transport layers.
/// </summary>
public interface IAgentProvider
{
    string ProviderId { get; }
    string ProviderName { get; }
    ProviderConfig Config { get; set; }

    /// <summary>
    /// Validates provider connectivity, credentials, and model responsiveness.
    /// </summary>
    Task<ConnectionTestResult> TestConnectionAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Generates a complete non-streaming chat completion.
    /// </summary>
    Task<ChatCompletionResponse> GenerateResponseAsync(ChatCompletionRequest request, CancellationToken cancellationToken = default);

    /// <summary>
    /// Streams tokens asynchronously as they are generated by the model.
    /// </summary>
    IAsyncEnumerable<string> StreamResponseAsync(ChatCompletionRequest request, CancellationToken cancellationToken = default);

    /// <summary>
    /// Backward-compatible lightweight validation check.
    /// </summary>
    async Task<bool> ValidateConnectionAsync(CancellationToken cancellationToken = default)
    {
        var result = await TestConnectionAsync(cancellationToken);
        return result.IsSuccess;
    }

    /// <summary>
    /// Backward-compatible text generation from simple message history.
    /// </summary>
    async Task<string> GenerateResponseAsync(IEnumerable<AgentMessage> history, CancellationToken cancellationToken = default)
    {
        var request = new ChatCompletionRequest(history.ToList());
        var response = await GenerateResponseAsync(request, cancellationToken);
        return response.Content;
    }
}

/// <summary>
/// Agent task planner interface.
/// </summary>
public interface IAgentPlanner
{
    Task<IReadOnlyList<ToolCall>> PlanTaskStepsAsync(AgentTask task, CancellationToken cancellationToken = default);
}
